#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCIMS_Software.SqlObjects
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PCIMS")]
	public partial class InvoiceDetailsSQLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public InvoiceDetailsSQLDataContext() : 
				base(global::PCIMS_Software.Properties.Settings.Default.PCIMSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public InvoiceDetailsSQLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InvoiceDetailsSQLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InvoiceDetailsSQLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InvoiceDetailsSQLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<InvoiceDetail> InvoiceDetails
		{
			get
			{
				return this.GetTable<InvoiceDetail>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.InvoiceDetail")]
	public partial class InvoiceDetail
	{
		
		private int _DtlNbr;
		
		private int _JobNbr;
		
		private string _ServiceCode;
		
		private string _ServiceDesc;
		
		private System.Nullable<double> _Quantity;
		
		private string _Unit;
		
		private System.Nullable<double> _UnitPrice;
		
		private System.Nullable<decimal> _Amount;
		
		private System.Nullable<double> _LineSplit;
		
		private System.Nullable<double> _LineDisc;
		
		private System.Nullable<decimal> _LineTotal;
		
		private System.Nullable<int> _LineNbr;
		
		public InvoiceDetail()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DtlNbr", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int DtlNbr
		{
			get
			{
				return this._DtlNbr;
			}
			set
			{
				if ((this._DtlNbr != value))
				{
					this._DtlNbr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobNbr", DbType="Int NOT NULL")]
		public int JobNbr
		{
			get
			{
				return this._JobNbr;
			}
			set
			{
				if ((this._JobNbr != value))
				{
					this._JobNbr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceCode", DbType="Char(4)")]
		public string ServiceCode
		{
			get
			{
				return this._ServiceCode;
			}
			set
			{
				if ((this._ServiceCode != value))
				{
					this._ServiceCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceDesc", DbType="NVarChar(50)")]
		public string ServiceDesc
		{
			get
			{
				return this._ServiceDesc;
			}
			set
			{
				if ((this._ServiceDesc != value))
				{
					this._ServiceDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Float")]
		public System.Nullable<double> Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit", DbType="NVarChar(6)")]
		public string Unit
		{
			get
			{
				return this._Unit;
			}
			set
			{
				if ((this._Unit != value))
				{
					this._Unit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitPrice", DbType="Float")]
		public System.Nullable<double> UnitPrice
		{
			get
			{
				return this._UnitPrice;
			}
			set
			{
				if ((this._UnitPrice != value))
				{
					this._UnitPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Money")]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this._Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineSplit", DbType="Float")]
		public System.Nullable<double> LineSplit
		{
			get
			{
				return this._LineSplit;
			}
			set
			{
				if ((this._LineSplit != value))
				{
					this._LineSplit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineDisc", DbType="Float")]
		public System.Nullable<double> LineDisc
		{
			get
			{
				return this._LineDisc;
			}
			set
			{
				if ((this._LineDisc != value))
				{
					this._LineDisc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineTotal", DbType="Money")]
		public System.Nullable<decimal> LineTotal
		{
			get
			{
				return this._LineTotal;
			}
			set
			{
				if ((this._LineTotal != value))
				{
					this._LineTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineNbr", DbType="Int")]
		public System.Nullable<int> LineNbr
		{
			get
			{
				return this._LineNbr;
			}
			set
			{
				if ((this._LineNbr != value))
				{
					this._LineNbr = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
