<?xml version="1.0" encoding="utf-8"?><Database Name="PCIMS" Class="InvoiceDetailsSQLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=NOBILSQLSERVER\MSSQLSERVER;Initial Catalog=PCIMS;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="PCIMS_Software.Properties.Settings" SettingsPropertyName="PCIMSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.InvoiceDetail" Member="InvoiceDetails">
    <Type Name="InvoiceDetail">
      <Column Name="DtlNbr" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="JobNbr" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ServiceCode" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="ServiceDesc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="UnitPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="LineSplit" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LineDisc" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LineTotal" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="LineNbr" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>