#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCIMS_Software.SqlObjects
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PCIMS")]
	public partial class JobTemplatesSQLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public JobTemplatesSQLDataContext() : 
				base(global::PCIMS_Software.Properties.Settings.Default.PCIMSConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public JobTemplatesSQLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JobTemplatesSQLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JobTemplatesSQLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JobTemplatesSQLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<jobtemplate> jobtemplates
		{
			get
			{
				return this.GetTable<jobtemplate>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.jobtemplates")]
	public partial class jobtemplate
	{
		
		private int _DtlNbr;
		
		private int _TemplateId;
		
		private int _JobNbr;
		
		public jobtemplate()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DtlNbr", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int DtlNbr
		{
			get
			{
				return this._DtlNbr;
			}
			set
			{
				if ((this._DtlNbr != value))
				{
					this._DtlNbr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplateId", DbType="Int NOT NULL")]
		public int TemplateId
		{
			get
			{
				return this._TemplateId;
			}
			set
			{
				if ((this._TemplateId != value))
				{
					this._TemplateId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobNbr", DbType="Int NOT NULL")]
		public int JobNbr
		{
			get
			{
				return this._JobNbr;
			}
			set
			{
				if ((this._JobNbr != value))
				{
					this._JobNbr = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
