<?xml version="1.0" encoding="utf-8"?><Database Name="PCIMS" Class="LabDetailsSQLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=NOBILSQLSERVER\MSSQLSERVER;Initial Catalog=PCIMS;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="PCIMS_Software.Properties.Settings" SettingsPropertyName="PCIMSConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.labdetail" Member="labdetails">
    <Type Name="labdetail">
      <Column Name="DtlNbr" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="JobNbr" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SheetNbr" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="LineNbr" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Marked" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="Re" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="Test" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="TestId" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="Astm" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="CompBy" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="Result" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Spec" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="Fee" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(140)" CanBeNull="true" />
      <Column Name="ReleaseId" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
    </Type>
  </Table>
</Database>