#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCIMS_Software.SqlObjects
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PCIMS")]
	public partial class LabDetailsSQLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public LabDetailsSQLDataContext() : 
				base(global::PCIMS_Software.Properties.Settings.Default.PCIMSConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public LabDetailsSQLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LabDetailsSQLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LabDetailsSQLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LabDetailsSQLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<labdetail> labdetails
		{
			get
			{
				return this.GetTable<labdetail>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.labdetail")]
	public partial class labdetail
	{
		
		private int _DtlNbr;
		
		private int _JobNbr;
		
		private System.Nullable<short> _SheetNbr;
		
		private System.Nullable<short> _LineNbr;
		
		private string _Marked;
		
		private string _Re;
		
		private string _Test;
		
		private string _TestId;
		
		private string _Astm;
		
		private string _CompBy;
		
		private string _Result;
		
		private string _Spec;
		
		private System.Nullable<decimal> _Fee;
		
		private string _Note;
		
		private string _ReleaseId;
		
		public labdetail()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DtlNbr", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int DtlNbr
		{
			get
			{
				return this._DtlNbr;
			}
			set
			{
				if ((this._DtlNbr != value))
				{
					this._DtlNbr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobNbr", DbType="Int NOT NULL")]
		public int JobNbr
		{
			get
			{
				return this._JobNbr;
			}
			set
			{
				if ((this._JobNbr != value))
				{
					this._JobNbr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SheetNbr", DbType="SmallInt")]
		public System.Nullable<short> SheetNbr
		{
			get
			{
				return this._SheetNbr;
			}
			set
			{
				if ((this._SheetNbr != value))
				{
					this._SheetNbr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineNbr", DbType="SmallInt")]
		public System.Nullable<short> LineNbr
		{
			get
			{
				return this._LineNbr;
			}
			set
			{
				if ((this._LineNbr != value))
				{
					this._LineNbr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marked", DbType="NVarChar(60)")]
		public string Marked
		{
			get
			{
				return this._Marked;
			}
			set
			{
				if ((this._Marked != value))
				{
					this._Marked = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Re", DbType="NVarChar(6)")]
		public string Re
		{
			get
			{
				return this._Re;
			}
			set
			{
				if ((this._Re != value))
				{
					this._Re = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Test", DbType="NVarChar(80)")]
		public string Test
		{
			get
			{
				return this._Test;
			}
			set
			{
				if ((this._Test != value))
				{
					this._Test = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestId", DbType="NVarChar(12)")]
		public string TestId
		{
			get
			{
				return this._TestId;
			}
			set
			{
				if ((this._TestId != value))
				{
					this._TestId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Astm", DbType="NVarChar(32)")]
		public string Astm
		{
			get
			{
				return this._Astm;
			}
			set
			{
				if ((this._Astm != value))
				{
					this._Astm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompBy", DbType="NVarChar(6)")]
		public string CompBy
		{
			get
			{
				return this._CompBy;
			}
			set
			{
				if ((this._CompBy != value))
				{
					this._CompBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="NVarChar(20)")]
		public string Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this._Result = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Spec", DbType="NVarChar(60)")]
		public string Spec
		{
			get
			{
				return this._Spec;
			}
			set
			{
				if ((this._Spec != value))
				{
					this._Spec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fee", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Fee
		{
			get
			{
				return this._Fee;
			}
			set
			{
				if ((this._Fee != value))
				{
					this._Fee = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(140)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this._Note = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReleaseId", DbType="NVarChar(6)")]
		public string ReleaseId
		{
			get
			{
				return this._ReleaseId;
			}
			set
			{
				if ((this._ReleaseId != value))
				{
					this._ReleaseId = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
